swagger: '2.0'
info:
  version: '1.0'
  title: IMIconnect Profile API
  description: profile api after beehyv and product team changes
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: api.imiconnect.com
basePath: /resources/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /customerprofile:
    get:
      description: ''
      summary: Get Profile - Bulk
      tags:
      - Misc
      operationId: CustomerprofileGet
      produces:
      - application/json
      parameters:
      - name: customerId
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /customerprofile?customerId=4
          headers:
            Content-Type: application/json
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get Profile - Bulk
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    put:
      description: ''
      summary: Update Profile
      tags:
      - Misc
      operationId: CustomerprofilePut
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/UpdateProfilerequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PUT
          uri: /customerprofile
          headers:
            Content-Type: application/json
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
          body: "{\r\n   \"Records\":[\r\n      {\r\n         \r\n       \"customerId\":\"100077\",\r\n        \"Attributes\":{\r\n       \"name\": \"vijay akula\", //optional\r\n       \"email\": \"vijay.akula@imimobile.com\",//optional\r\n       \"msisdn\": \"919676534531\",//optional\r\n       \"city\":\"Hyderabad\",//optional\r\n      \"country\":\"India\",//optional\r\n      \"accountId\":\"100077\",//optional\r\n      \"clientId\":\"OHDevSanity\"//optional\r\n       \r\n         }\r\n      }, \r\n      \r\n      \r\n      {\r\n         \"customerId\":\"4\",\r\n       \r\n         \"Attributes\":{\r\n       \"name\": \"Mahesh Pavan\",\r\n       \"email\": \"pavankumar.g@imimobile.com\",\r\n       \"msisdn\": \"919703553010\",\r\n       \"city\":\"Hyderabad\",\r\n       \"country\":\"India\",\r\n       \"accountId\":\"100077\",\r\n       \"clientId\":\"OHDevSanity\"\r\n       \r\n         }\r\n      }\r\n   ]\r\n}"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Update Profile
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      description: ''
      summary: Create Profile
      tags:
      - Misc
      operationId: CustomerprofilePost
      produces:
      - application/json
      parameters:
      - name: key
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: POST
          uri: /customerprofile
          headers:
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
            Content-Type: application/json
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Create Profile
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      description: ''
      summary: Profile-Delete-Multiple
      tags:
      - Misc
      operationId: CustomerprofileDelete
      produces:
      - application/json
      parameters:
      - name: customerId
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: DELETE
          uri: /customerprofile?customerId=4545
          headers:
            Content-Type: application/json
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Profile-Delete-Multiple
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /a_635840479228873065/:
    post:
      description: ''
      summary: Create App Profile
      tags:
      - Misc
      operationId: A635840479228873065Post
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateAppProfilerequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: POST
          uri: /a_635840479228873065/
          headers:
            Content-Type: application/json
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
          body: "{\r\n   \"Records\":[\r\n      \r\n    {\r\n         //Facebook App profile \r\n         \"customerId\":\"100077\",\r\n         \"Attributes\":{\r\n         \r\n              \"fb_user_id\":\"1027581030637981\", //mandatory\r\n              \"fb_conversation_id\": \"t_mid.1453704265532:e9228e75c730b38079\",\r\n              \"status\": \"1\",//madatory\r\n              \"fbstatus\":\"1\", //optional\r\n              \"fbcstatus\":\"1\", //optional\r\n              \"verified\":\"1\",//optional\r\n              \"access_token\":\"CAAMRVlEvpz0BAGPrZAcxNJP6erVMODjWDI5zANTKuDXrKoJlzXH7hNcMkAqrCkPmLshmYfTO6ozpkEmGQeai3KEltbZBay3HygIBPhrj6qcojZBgD6qHROEJpz2taeeDs5DCGZCHPeVHRmIZCCWjP3BzeIVS7U81RdsHZAC0jbHQTDPu6j7Y1wJUj6pVRPhs4SnAdezGxAsQZDZD\",//optional\r\n              \"access_token_expiry\":\"5168517\",//optional\r\n              \"name\":\"Vijay Akula\",//optional\r\n              \"first_name\":\"Vijay\",//optional\r\n              \"middle_name\":\"\",//optional\r\n              \"last_name\":\"Akula\",//optional\r\n              \"gender\":\"male\",//optional\r\n              \"email\":\"vijaykumar5c1@gmail.com\",//optional\r\n              \"location\":\"102.0000,454.788\",//optional\r\n              \"birthday\":\"\"//optional\r\n\r\n\r\n         }\r\n      }     \r\n      \r\n      \r\n    //   //Twitter App Profile\r\n    //   {\r\n    //      \"customerId\":\"100077\",\r\n    //      \"Attributes\":{\r\n    //             \"twitter_user_id\":\"357282265\", //mandatory\r\n    //             \"status\": \"1\", //mandatory\r\n    //             \"verified\": \"1\", //optional\r\n    //             \"access_token\":\"\", //optional\r\n    //             \"access_tokensecret\":\"\",//optional\r\n    //             \"screenName\":\"vijaykumar5c1\", //optional\r\n    //             \"geolocation\":\"\",//optional\r\n    //             \"timezone\":\"Hawaii\"//optional\r\n\r\n    //      }\r\n    //   }\r\n      \r\n      \r\n      \r\n   ]\r\n}\r\n\r\n"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Create App Profile
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /customerprofile/5d730b72-f3ba-4250-a1d0-3f7fd0b5d962/:
    get:
      description: ''
      summary: Get Profile
      tags:
      - Misc
      operationId: Customerprofile5d730b72F3ba4250A1d03f7fd0b5d962Get
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /customerprofile/5d730b72-f3ba-4250-a1d0-3f7fd0b5d962/
          headers:
            Content-Type: application/json
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get Profile
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /a_635852551475226245/100077:
    get:
      description: ''
      summary: Get App Profile
      tags:
      - Misc
      operationId: A635852551475226245100077Get
      produces:
      - application/json
      parameters:
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /a_635852551475226245/100077
          headers:
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get App Profile
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /a_635852560539605550:
    put:
      description: ''
      summary: Update App Profile
      tags:
      - Misc
      operationId: A635852560539605550Put
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/UpdateAppProfilerequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PUT
          uri: /a_635852560539605550
          headers:
            Content-Type: application/json
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
          body: "{\r\n   \"Records\":[\r\n\r\n    //   {\r\n    //      //Facebook App profile \r\n    //      \"customerId\":\"100077\",\r\n    //      \"Attributes\":{\r\n         \r\n    //           \"fb_user_id\":\"1027581030637981\", //mandatory\r\n    //           \"fb_conversation_id\": \"t_mid.1453704265532:e9228e75c730b38079\",\r\n    //           \"status\": \"1\",//madatory\r\n    //           \"fbstatus\":\"1\", //optional\r\n    //           \"fbcstatus\":\"1\", //optional\r\n    //           \"verified\":\"1\",//optional\r\n    //           \"access_token\":\"CAAMRVlEvpz0BAGPrZAcxNJP6erVMODjWDI5zANTKuDXrKoJlzXH7hNcMkAqrCkPmLshmYfTO6ozpkEmGQeai3KEltbZBay3HygIBPhrj6qcojZBgD6qHROEJpz2taeeDs5DCGZCHPeVHRmIZCCWjP3BzeIVS7U81RdsHZAC0jbHQTDPu6j7Y1wJUj6pVRPhs4SnAdezGxAsQZDZD\",//optional\r\n    //           \"access_token_expiry\":\"5168517\",//optional\r\n    //           \"name\":\"Vijay Akula\",//optional\r\n    //           \"first_name\":\"Vijay\",//optional\r\n    //           \"middle_name\":\"\",//optional\r\n    //           \"last_name\":\"Akula\",//optional\r\n    //           \"gender\":\"male\",//optional\r\n    //           \"email\":\"vijaykumar5c1@gmail.com\",//optional\r\n    //           \"location\":\"102.0000,454.788\",//optional\r\n    //           \"birthday\":\"\"//optional\r\n\r\n\r\n    //      }\r\n    //   }     \r\n      \r\n      \r\n      //Twitter App Profile\r\n      {\r\n         \"customerId\":\"100077\",\r\n         \"Attributes\":{\r\n                \"twitter_user_id\":\"357282265\", //mandatory\r\n                \"status\": \"1\", //mandatory\r\n                \"verified\": \"1\", //optional\r\n                \"access_token\":\"\", //optional\r\n                \"access_tokensecret\":\"\",//optional\r\n                \"screenName\":\"vijaykumar5c1\", //optional\r\n                \"geolocation\":\"\",//optional\r\n                \"timezone\":\"Hawaii\"//optional\r\n\r\n         }\r\n      }\r\n      \r\n      \r\n      \r\n      \r\n   ]\r\n}"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Update App Profile
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /customerprofile/7878:
    delete:
      description: ''
      summary: Delete Profile
      tags:
      - Misc
      operationId: Customerprofile7878Delete
      produces:
      - application/json
      parameters:
      - name: showinwardlinks
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: DELETE
          uri: /customerprofile/7878?showinwardlinks=2
          headers:
            Content-Type: application/json
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Delete Profile
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /a_635845757632550116/2106:
    delete:
      description: ''
      summary: Delete App Profile
      tags:
      - Misc
      operationId: A6358457576325501162106Delete
      produces:
      - application/json
      parameters:
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: DELETE
          uri: /a_635845757632550116/2106
          headers:
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Delete App Profile
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /a_635852551475226245:
    get:
      description: ''
      summary: Get App Profile - Bulk
      tags:
      - Misc
      operationId: A635852551475226245Get
      produces:
      - application/json
      parameters:
      - name: customerId
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /a_635852551475226245?customerId=4545
          headers:
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get App Profile - Bulk
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /a_635840479228873065:
    delete:
      description: ''
      summary: Get App Profile - Multiple
      tags:
      - Misc
      operationId: A635840479228873065Delete
      produces:
      - application/json
      parameters:
      - name: customerId
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      - name: key
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: DELETE
          uri: /a_635840479228873065?customerId=2134
          headers:
            key: 6ec2cc03-1d28-4b56-9ecd-42e44c8678410
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get App Profile - Multiple
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  CreateAppProfilerequest:
    title: Create App ProfileRequest
    example:
      Records:
      - customerId: 100077
        Attributes:
          fb_user_id: 1027581030637981
          fb_conversation_id: t_mid.1453704265532:e9228e75c730b38079
          status: 1
          fbstatus: 1
          fbcstatus: 1
          verified: 1
          access_token: CAAMRVlEvpz0BAGPrZAcxNJP6erVMODjWDI5zANTKuDXrKoJlzXH7hNcMkAqrCkPmLshmYfTO6ozpkEmGQeai3KEltbZBay3HygIBPhrj6qcojZBgD6qHROEJpz2taeeDs5DCGZCHPeVHRmIZCCWjP3BzeIVS7U81RdsHZAC0jbHQTDPu6j7Y1wJUj6pVRPhs4SnAdezGxAsQZDZD
          access_token_expiry: 5168517
          name: Vijay Akula
          first_name: Vijay
          middle_name: ''
          last_name: Akula
          gender: male
          email: vijaykumar5c1@gmail.com
          location: 102.0000,454.788
          birthday: ''
    type: object
    properties:
      Records:
        description: ''
        example:
        - customerId: 100077
          Attributes:
            fb_user_id: 1027581030637981
            fb_conversation_id: t_mid.1453704265532:e9228e75c730b38079
            status: 1
            fbstatus: 1
            fbcstatus: 1
            verified: 1
            access_token: CAAMRVlEvpz0BAGPrZAcxNJP6erVMODjWDI5zANTKuDXrKoJlzXH7hNcMkAqrCkPmLshmYfTO6ozpkEmGQeai3KEltbZBay3HygIBPhrj6qcojZBgD6qHROEJpz2taeeDs5DCGZCHPeVHRmIZCCWjP3BzeIVS7U81RdsHZAC0jbHQTDPu6j7Y1wJUj6pVRPhs4SnAdezGxAsQZDZD
            access_token_expiry: 5168517
            name: Vijay Akula
            first_name: Vijay
            middle_name: ''
            last_name: Akula
            gender: male
            email: vijaykumar5c1@gmail.com
            location: 102.0000,454.788
            birthday: ''
        type: array
        items:
          $ref: '#/definitions/Record'
    required:
    - Records
  Record:
    title: Record
    example:
      customerId: 100077
      Attributes:
        fb_user_id: 1027581030637981
        fb_conversation_id: t_mid.1453704265532:e9228e75c730b38079
        status: 1
        fbstatus: 1
        fbcstatus: 1
        verified: 1
        access_token: CAAMRVlEvpz0BAGPrZAcxNJP6erVMODjWDI5zANTKuDXrKoJlzXH7hNcMkAqrCkPmLshmYfTO6ozpkEmGQeai3KEltbZBay3HygIBPhrj6qcojZBgD6qHROEJpz2taeeDs5DCGZCHPeVHRmIZCCWjP3BzeIVS7U81RdsHZAC0jbHQTDPu6j7Y1wJUj6pVRPhs4SnAdezGxAsQZDZD
        access_token_expiry: 5168517
        name: Vijay Akula
        first_name: Vijay
        middle_name: ''
        last_name: Akula
        gender: male
        email: vijaykumar5c1@gmail.com
        location: 102.0000,454.788
        birthday: ''
    type: object
    properties:
      customerId:
        description: ''
        example: 100077
        type: string
      Attributes:
        $ref: '#/definitions/Attributes'
    required:
    - customerId
    - Attributes
  Attributes:
    title: Attributes
    example:
      fb_user_id: 1027581030637981
      fb_conversation_id: t_mid.1453704265532:e9228e75c730b38079
      status: 1
      fbstatus: 1
      fbcstatus: 1
      verified: 1
      access_token: CAAMRVlEvpz0BAGPrZAcxNJP6erVMODjWDI5zANTKuDXrKoJlzXH7hNcMkAqrCkPmLshmYfTO6ozpkEmGQeai3KEltbZBay3HygIBPhrj6qcojZBgD6qHROEJpz2taeeDs5DCGZCHPeVHRmIZCCWjP3BzeIVS7U81RdsHZAC0jbHQTDPu6j7Y1wJUj6pVRPhs4SnAdezGxAsQZDZD
      access_token_expiry: 5168517
      name: Vijay Akula
      first_name: Vijay
      middle_name: ''
      last_name: Akula
      gender: male
      email: vijaykumar5c1@gmail.com
      location: 102.0000,454.788
      birthday: ''
    type: object
    properties:
      fb_user_id:
        description: ''
        example: 1027581030637981
        type: string
      fb_conversation_id:
        description: ''
        example: t_mid.1453704265532:e9228e75c730b38079
        type: string
      status:
        description: ''
        example: 1
        type: string
      fbstatus:
        description: ''
        example: 1
        type: string
      fbcstatus:
        description: ''
        example: 1
        type: string
      verified:
        description: ''
        example: 1
        type: string
      access_token:
        description: ''
        example: CAAMRVlEvpz0BAGPrZAcxNJP6erVMODjWDI5zANTKuDXrKoJlzXH7hNcMkAqrCkPmLshmYfTO6ozpkEmGQeai3KEltbZBay3HygIBPhrj6qcojZBgD6qHROEJpz2taeeDs5DCGZCHPeVHRmIZCCWjP3BzeIVS7U81RdsHZAC0jbHQTDPu6j7Y1wJUj6pVRPhs4SnAdezGxAsQZDZD
        type: string
      access_token_expiry:
        description: ''
        example: 5168517
        type: string
      name:
        description: ''
        example: Vijay Akula
        type: string
      first_name:
        description: ''
        example: Vijay
        type: string
      middle_name:
        description: ''
        type: string
      last_name:
        description: ''
        example: Akula
        type: string
      gender:
        description: ''
        example: male
        type: string
      email:
        description: ''
        example: vijaykumar5c1@gmail.com
        type: string
      location:
        description: ''
        example: 102.0000,454.788
        type: string
      birthday:
        description: ''
        type: string
    required:
    - fb_user_id
    - fb_conversation_id
    - status
    - fbstatus
    - fbcstatus
    - verified
    - access_token
    - access_token_expiry
    - name
    - first_name
    - middle_name
    - last_name
    - gender
    - email
    - location
    - birthday
  UpdateProfilerequest:
    title: Update ProfileRequest
    example:
      Records:
      - customerId: 100077
        Attributes:
          name: vijay akula
          email: vijay.akula@imimobile.com
          msisdn: 919676534531
          city: Hyderabad
          country: India
          accountId: 100077
          clientId: OHDevSanity
      - customerId: 4
        Attributes:
          name: Mahesh Pavan
          email: pavankumar.g@imimobile.com
          msisdn: 919703553010
          city: Hyderabad
          country: India
          accountId: 100077
          clientId: OHDevSanity
    type: object
    properties:
      Records:
        description: ''
        example:
        - customerId: 100077
          Attributes:
            name: vijay akula
            email: vijay.akula@imimobile.com
            msisdn: 919676534531
            city: Hyderabad
            country: India
            accountId: 100077
            clientId: OHDevSanity
        - customerId: 4
          Attributes:
            name: Mahesh Pavan
            email: pavankumar.g@imimobile.com
            msisdn: 919703553010
            city: Hyderabad
            country: India
            accountId: 100077
            clientId: OHDevSanity
        type: array
        items:
          $ref: '#/definitions/Record4'
    required:
    - Records
  Record4:
    title: Record4
    example:
      customerId: 100077
      Attributes:
        name: vijay akula
        email: vijay.akula@imimobile.com
        msisdn: 919676534531
        city: Hyderabad
        country: India
        accountId: 100077
        clientId: OHDevSanity
    type: object
    properties:
      customerId:
        description: ''
        example: 100077
        type: string
      Attributes:
        $ref: '#/definitions/Attributes5'
    required:
    - customerId
    - Attributes
  Attributes5:
    title: Attributes5
    example:
      name: vijay akula
      email: vijay.akula@imimobile.com
      msisdn: 919676534531
      city: Hyderabad
      country: India
      accountId: 100077
      clientId: OHDevSanity
    type: object
    properties:
      name:
        description: ''
        example: vijay akula
        type: string
      email:
        description: ''
        example: vijay.akula@imimobile.com
        type: string
      msisdn:
        description: ''
        example: 919676534531
        type: string
      city:
        description: ''
        example: Hyderabad
        type: string
      country:
        description: ''
        example: India
        type: string
      accountId:
        description: ''
        example: 100077
        type: string
      clientId:
        description: ''
        example: OHDevSanity
        type: string
    required:
    - name
    - email
    - msisdn
    - city
    - country
    - accountId
    - clientId
  UpdateAppProfilerequest:
    title: Update App ProfileRequest
    example:
      Records:
      - customerId: 100077
        Attributes:
          twitter_user_id: 357282265
          status: 1
          verified: 1
          access_token: ''
          access_tokensecret: ''
          screenName: vijaykumar5c1
          geolocation: ''
          timezone: Hawaii
    type: object
    properties:
      Records:
        description: ''
        example:
        - customerId: 100077
          Attributes:
            twitter_user_id: 357282265
            status: 1
            verified: 1
            access_token: ''
            access_tokensecret: ''
            screenName: vijaykumar5c1
            geolocation: ''
            timezone: Hawaii
        type: array
        items:
          $ref: '#/definitions/Record7'
    required:
    - Records
  Record7:
    title: Record7
    example:
      customerId: 100077
      Attributes:
        twitter_user_id: 357282265
        status: 1
        verified: 1
        access_token: ''
        access_tokensecret: ''
        screenName: vijaykumar5c1
        geolocation: ''
        timezone: Hawaii
    type: object
    properties:
      customerId:
        description: ''
        example: 100077
        type: string
      Attributes:
        $ref: '#/definitions/Attributes8'
    required:
    - customerId
    - Attributes
  Attributes8:
    title: Attributes8
    example:
      twitter_user_id: 357282265
      status: 1
      verified: 1
      access_token: ''
      access_tokensecret: ''
      screenName: vijaykumar5c1
      geolocation: ''
      timezone: Hawaii
    type: object
    properties:
      twitter_user_id:
        description: ''
        example: 357282265
        type: string
      status:
        description: ''
        example: 1
        type: string
      verified:
        description: ''
        example: 1
        type: string
      access_token:
        description: ''
        type: string
      access_tokensecret:
        description: ''
        type: string
      screenName:
        description: ''
        example: vijaykumar5c1
        type: string
      geolocation:
        description: ''
        type: string
      timezone:
        description: ''
        example: Hawaii
        type: string
    required:
    - twitter_user_id
    - status
    - verified
    - access_token
    - access_tokensecret
    - screenName
    - geolocation
    - timezone
